

# This file was *autogenerated* from the file 1-(x+1)(y+2)-prob/monomial_order.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_3 = Integer(3)
_sage_const_5 = Integer(5)
_sage_const_10 = Integer(10)
_sage_const_100 = Integer(100)
_sage_const_99 = Integer(99)
_sage_const_4 = Integer(4)
_sage_const_11 = Integer(11)
_sage_const_1919810 = Integer(1919810)
_sage_const_0 = Integer(0)
_sage_const_114514 = Integer(114514)
R = PolynomialRing(QQ, order='lex', names=('t', 'x', 'y',))
(t, x, y,) = R._first_ngens(3)

mon_order = R.term_order()
print('单项式序类型：', mon_order)
print('变量优先级（从高到低）：', R.variable_names(), '\n')

m1 = t ** _sage_const_2 * x * y ** _sage_const_3
m2 = t ** _sage_const_2 * x ** _sage_const_2
m3 = t * x ** _sage_const_5 * y ** _sage_const_10
m4 = x ** _sage_const_3 * y
m5 = y ** _sage_const_100
m6 = t ** _sage_const_2 * x * y ** _sage_const_2   # 与 m1 比，仅 y 指数不同
m7 = _sage_const_3 * t ** _sage_const_2 * x ** _sage_const_2   # 与 m2 比，仅系数不同
m8 = x ** _sage_const_2 * y ** _sage_const_99
m9 = t * x ** _sage_const_4 * y ** _sage_const_11
m10 = x ** _sage_const_2 * y ** _sage_const_2
m11 = _sage_const_1919810 * y ** _sage_const_0
m12 = _sage_const_114514 * y ** _sage_const_100
m13 = _sage_const_2 * t ** _sage_const_2 * x ** _sage_const_2

monomials = [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13]

print('单项式及其指数元组 (t, x, y)：')
for m in monomials:
    exp_tuple = m.exponents()[_sage_const_0]
    print(f'{m}  ->  {exp_tuple}')

print('\n按 lex 顺序从大到小排序：')
sorted_mons = sorted(monomials, reverse=True)
for m in sorted_mons:
    exp_tuple = m.exponents()[_sage_const_0]
    print(f'{m}  ->  {exp_tuple}')
'''
3*t^2*x^2  ->  (2, 2, 0)
2*t^2*x^2  ->  (2, 2, 0)
t^2*x^2  ->  (2, 2, 0)
t^2*x*y^3  ->  (2, 1, 3)
t^2*x*y^2  ->  (2, 1, 2)
t*x^5*y^10  ->  (1, 5, 10)
t*x^4*y^11  ->  (1, 4, 11)
x^3*y  ->  (0, 3, 1)
x^2*y^99  ->  (0, 2, 99)
x^2*y^2  ->  (0, 2, 2)
114514*y^100  ->  (0, 0, 100)
y^100  ->  (0, 0, 100)
1919810  ->  (0, 0, 0)
'''
