

# This file was *autogenerated* from the file 1-(x+1)(y+2)-prob/solve_directly.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_1 = Integer(1)
x, y, t = var('x y t')
sols = solve([_sage_const_2 * t * x + y + _sage_const_2, _sage_const_2 * t * y + x + _sage_const_1, x ** _sage_const_2 + y ** _sage_const_2 - _sage_const_1])
print(sols)
'''
[
[y == 0.576378809869376, x == 0.8171826341820846, t == -1.576378721327477],
[y == (-1.2881894005025987 + 0.27484212321137874*I), x == (-0.40859132325338593 - 0.8665105933073517*I), t == (0.28818940050259856 - 0.2748421232113787*I)],
[y == (-1.2881894005025987 - 0.27484212321137874*I), x == (-0.40859132325338593 + 0.8665105933073517*I), t == (0.28818940050259856 + 0.2748421232113787*I)],
[y == 0, x == -1, t == 1]
]
'''
