

# This file was *autogenerated* from the file 5-绝谷野樵化简根式/solve3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_3 = Integer(3)
_sage_const_6 = Integer(6)
_sage_const_45 = Integer(45)
_sage_const_4 = Integer(4)
_sage_const_135 = Integer(135)
_sage_const_27 = Integer(27)
_sage_const_360 = Integer(360)
_sage_const_1080 = Integer(1080)
_sage_const_180 = Integer(180)
_sage_const_540 = Integer(540)
_sage_const_18 = Integer(18)
_sage_const_36 = Integer(36)
_sage_const_1 = Integer(1)
_sage_const_5 = Integer(5)
_sage_const_60 = Integer(60)
_sage_const_54 = Integer(54)
_sage_const_30 = Integer(30)
_sage_const_270 = Integer(270)
_sage_const_24 = Integer(24)
_sage_const_12 = Integer(12)
_sage_const_72 = Integer(72)
_sage_const_40 = Integer(40)
_sage_const_9 = Integer(9)
import re
load('5-绝谷野樵化简根式/sqrt236_shared.sage')


def solve_equation_phase1(c1):
    R = QQ['x']
    (x,) = R._first_ngens(1)
    K = NumberField([x ** _sage_const_2 - _sage_const_3], names=('s3',))
    (s3,) = K._first_ngens(1)
    L = K.extension(x ** _sage_const_2 - _sage_const_2 * s3, names=('s12',))
    (s12,) = L._first_ngens(1)
    S = PolynomialRing(L, names=('a', 'b', 'c',))
    (a, b, c,) = S._first_ngens(3)
    expr = ((a + b * s3 + c * s12) ** _sage_const_3 - c1) ** _sage_const_2
    print(expr)


def get_eqs(s):
    s_clean = re.sub(r'\s+', ' ', s.strip())
    terms = [term.strip() for term in s_clean.split('+') if term.strip()]

    type1 = []  # 无 s3, 无 s12
    type2 = []  # 有 s3, 无 s12
    type3 = []  # 无 s3, 有 s12
    type4 = []  # 有 s3, 有 s12

    for term in terms:
        has_s3 = 's3' in term
        has_s12 = 's12' in term

        if has_s3 and has_s12:
            coeff = term.replace('*s3*s12', '')
            type4.append(coeff)
        elif has_s3:
            coeff = term.replace('*s3', '')
            type2.append(coeff)
        elif has_s12:
            coeff = term.replace('*s12', '')
            type3.append(coeff)
        else:
            type1.append(term)

    eq1 = ' + '.join(type1) if type1 else '0'
    eq2 = ' + '.join(type2) if type2 else '0'
    eq3 = ' + '.join(type3) if type3 else '0'
    eq4 = ' + '.join(type4) if type4 else '0'
    return eq1, eq2, eq3, eq4


def solve_equation_phase2(c2, c3):
    s = '''
    a^6 + 6*s3*a^5*b + 45*a^4*b^2 + 60*s3*a^3*b^3 + 135*a^2*b^4 + 54*s3*a*b^5 + 27*b^6
    + 6*s12*a^5*c + 30*s3*s12*a^4*b*c + 180*s12*a^3*b^2*c + 180*s3*s12*a^2*b^3*c
    + 270*s12*a*b^4*c + 54*s3*s12*b^5*c + 30*s3*a^4*c^2 + 360*a^3*b*c^2 + 540*s3*a^2*b^2*c^2
    + 1080*a*b^3*c^2 + 270*s3*b^4*c^2 + 40*s3*s12*a^3*c^3 + 360*s12*a^2*b*c^3 +
    360*s3*s12*a*b^2*c^3 + 360*s12*b^3*c^3 + 180*a^2*c^4 + 360*s3*a*b*c^4 +
    540*b^2*c^4 + 72*s12*a*c^5 + 72*s3*s12*b*c^5 + 24*s3*c^6 + (-2)*a^3 + (-6*s3)*a^2*b
    + (-18)*a*b^2 + (-6*s3)*b^3 + (-6*s12)*a^2*c + (-12*s3*s12)*a*b*c + (-18*s12)*b^2*c
    + (-12*s3)*a*c^2 + (-36)*b*c^2 + (-4*s3*s12)*c^3 + 1
    '''
    eq1, eq2, eq3, eq4 = get_eqs(s)
    print(eq1)
    print(eq2)
    print(eq3)
    print(eq4)

    S = PolynomialRing(QQ, order='lex', names=('a', 'b', 'c',))
    (a, b, c,) = S._first_ngens(3)
    eq1 = a ** _sage_const_6 + _sage_const_45 * a ** _sage_const_4 * b ** _sage_const_2 + _sage_const_135 * a ** _sage_const_2 * b ** _sage_const_4 + _sage_const_27 * b ** _sage_const_6 + _sage_const_360 * a ** _sage_const_3 * b * c ** _sage_const_2 + _sage_const_1080 * a * b ** _sage_const_3 * \
        c ** _sage_const_2 + _sage_const_180 * a ** _sage_const_2 * c ** _sage_const_4 + _sage_const_540 * b ** _sage_const_2 * c ** _sage_const_4 + (-_sage_const_2) * a ** _sage_const_3 + (-_sage_const_18) * a * b ** _sage_const_2 + (-_sage_const_36) * b * c ** _sage_const_2 + _sage_const_1 - c2
    eq2 = _sage_const_6 * a ** _sage_const_5 * b + _sage_const_60 * a ** _sage_const_3 * b ** _sage_const_3 + _sage_const_54 * a * b ** _sage_const_5 + _sage_const_30 * a ** _sage_const_4 * c ** _sage_const_2 + _sage_const_540 * a ** _sage_const_2 * b ** _sage_const_2 * c ** _sage_const_2 + \
        _sage_const_270 * b ** _sage_const_4 * c ** _sage_const_2 + _sage_const_360 * a * b * c ** _sage_const_4 + _sage_const_24 * c ** _sage_const_6 + (-_sage_const_6) * a ** _sage_const_2 * b + (-_sage_const_6) * b ** _sage_const_3 + (-_sage_const_12) * a * c ** _sage_const_2 - c3
    eq3 = _sage_const_6 * a ** _sage_const_5 * c + _sage_const_180 * a ** _sage_const_3 * b ** _sage_const_2 * c + _sage_const_270 * a * b ** _sage_const_4 * c + _sage_const_360 * a ** _sage_const_2 * b * \
        c ** _sage_const_3 + _sage_const_360 * b ** _sage_const_3 * c ** _sage_const_3 + _sage_const_72 * a * c ** _sage_const_5 + (-_sage_const_6) * a ** _sage_const_2 * c + (-_sage_const_18) * b ** _sage_const_2 * c
    eq4 = _sage_const_30 * a ** _sage_const_4 * b * c + _sage_const_180 * a ** _sage_const_2 * b ** _sage_const_3 * c + _sage_const_54 * b ** _sage_const_5 * c + _sage_const_40 * a ** _sage_const_3 * \
        c ** _sage_const_3 + _sage_const_360 * a * b ** _sage_const_2 * c ** _sage_const_3 + _sage_const_72 * b * c ** _sage_const_5 + (-_sage_const_12) * a * b * c + (-_sage_const_4) * c ** _sage_const_3
    G = ideal(eq1, eq2, eq3, eq4).groebner_basis()
    for i, g in enumerate(G):
        print(f'G[{i}] =', g)
    last_var_poly = G[-_sage_const_1].factor()
    print(last_var_poly)
    last_var = c
    sols = solve(SR(last_var_poly), SR(last_var))
    sols = [sol.rhs() for sol in sols if sol.rhs().is_real()]
    var_list = (a, b, c)
    wanted = back_substitution_with_a_sol(G, last_var, var_list, {last_var: _sage_const_1 / _sage_const_2})
    print(wanted)
    return G, last_var, var_list, sols

# 下面3种方法全部失败
# v1 = expr.coefficient({s3:0, s12:0})
# v2 = expr.coefficient({s3:1, s12:0})
# v3 = expr.coefficient({s3:0, s12:1})
# v4 = expr.coefficient({s3:1, s12:1})
# v1 = expr.subs({s3:0, s12:0})
# v2 = expr.subs({s3:1, s12:0})
# v3 = expr.subs({s3:0, s12:1})
# v4 = expr.subs({s3:1, s12:1})
# print(v1, type(v1))
# print(v2)

# xx = expr.polynomial(s12)
# print(xx)

# V, from_V, to_V = L.relative_vector_space()
# vec_eq = to_V(expr)
# print(vec_eq)
# eqs = [SR(comp) == 0 for comp in vec_eq]


# solve_equation_phase1(1)
solve_equation_phase2(-_sage_const_9, _sage_const_6)
