

# This file was *autogenerated* from the file 5-绝谷野樵化简根式/sqrt_exp.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_3 = Integer(3)
_sage_const_11 = Integer(11)
_sage_const_9 = Integer(9)
_sage_const_6 = Integer(6)
_sage_const_5 = Integer(5)
_sage_const_1 = Integer(1)
_sage_const_0 = Integer(0)
_sage_const_7 = Integer(7)
_sage_const_4 = Integer(4)
_sage_const_8 = Integer(8)
_sage_const_1028 = Integer(1028)
_sage_const_1159 = Integer(1159)
_sage_const_4336 = Integer(4336)
_sage_const_6551 = Integer(6551)
_sage_const_18 = Integer(18)
_sage_const_67 = Integer(67)
_sage_const_233 = Integer(233)
_sage_const_24 = Integer(24)
K = NumberField([x ** _sage_const_2 - _sage_const_2, x ** _sage_const_2 - _sage_const_3], names=('sqrt2', 'sqrt3',))
(sqrt2, sqrt3,) = K._first_ngens(2)
sqrt6 = sqrt2 * sqrt3
expr = _sage_const_11 * sqrt2 + _sage_const_9 * sqrt3
result1 = expr ** _sage_const_6
result2 = expr ** _sage_const_5
v1 = result1.vector()
v2 = result2.vector()
print(result1, type(result1), v1)
print(result2, type(result2), v2)
vv1 = v1[_sage_const_1].vector()
vv2 = v2[_sage_const_0].vector()
print(vv1, type(vv1))
print(vv2, type(vv2))

expr2 = _sage_const_7 + _sage_const_3 * sqrt2 + _sage_const_2 * sqrt3
result21 = expr2 ** _sage_const_5
print(result21)

expr3 = -_sage_const_1 + sqrt2 + sqrt3
result31 = expr3 ** _sage_const_5
print(result31)

print('5-绝谷野樵化简根式/solve_sqrt236.sage 的验算：')
val1 = (_sage_const_7 / _sage_const_6 * sqrt6 + _sage_const_4 / _sage_const_3 * sqrt3 + _sage_const_3 / _sage_const_2 * sqrt2 + _sage_const_8) ** _sage_const_3 - \
    (_sage_const_1028 + _sage_const_1159 / _sage_const_2 * sqrt2 + _sage_const_4336 / _sage_const_9 * sqrt3 + _sage_const_6551 / _sage_const_18 * sqrt6)
val2 = (_sage_const_1 / _sage_const_6 * sqrt6 + _sage_const_1 / _sage_const_3 * sqrt3 + _sage_const_1 / _sage_const_2 * sqrt2 +
        _sage_const_1) ** _sage_const_2 - (_sage_const_2 + _sage_const_4 / _sage_const_3 * sqrt2 + sqrt3 + _sage_const_2 / _sage_const_3 * sqrt6)
val3 = (sqrt3 + _sage_const_7 / _sage_const_6 * sqrt6) ** _sage_const_2 - (_sage_const_67 / _sage_const_6 + _sage_const_7 * sqrt2)
val4 = (_sage_const_1 + _sage_const_4 / _sage_const_3 * sqrt3 + _sage_const_3 / _sage_const_4 * sqrt6) ** _sage_const_2 - \
    (_sage_const_233 / _sage_const_24 + _sage_const_6 * sqrt2 + _sage_const_8 / _sage_const_3 * sqrt3 + _sage_const_3 / _sage_const_2 * sqrt6)
print(val1, val2, val3, val4)

'''
186298002*sqrt3*sqrt2 + 456335045 <class 'sage.rings.number_field.number_field_element.NumberFieldElement_relative'> (456335045, 186298002*sqrt3)
10360559*sqrt2 + 8459361*sqrt3 <class 'sage.rings.number_field.number_field_element.NumberFieldElement_relative'> (8459361*sqrt3, 10360559)
(0, 186298002) <class 'sage.modules.vector_rational_dense.Vector_rational_dense'>
(0, 8459361) <class 'sage.modules.vector_rational_dense.Vector_rational_dense'>
(66360*sqrt3 + 125007)*sqrt2 + 96538*sqrt3 + 181447
(-120*sqrt3 + 224)*sqrt2 + 184*sqrt3 - 296
'''
