

# This file was *autogenerated* from the file 5-绝谷野樵化简根式/八蛮献宝_失败.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_3 = Integer(3)
_sage_const_5 = Integer(5)
_sage_const_0 = Integer(0)
_sage_const_1 = Integer(1)
_sage_const_6 = Integer(6)
_sage_const_9 = Integer(9)
_sage_const_15 = Integer(15)
_sage_const_18 = Integer(18)
_sage_const_30 = Integer(30)
_sage_const_45 = Integer(45)
_sage_const_90 = Integer(90)
_sage_const_36 = Integer(36)
_sage_const_60 = Integer(60)
_sage_const_180 = Integer(180)
_sage_const_12 = Integer(12)
_sage_const_10 = Integer(10)
_sage_const_2848 = Integer(2848)
_sage_const_135 = Integer(135)
_sage_const_1213 = Integer(1213)
_sage_const_704 = Integer(704)
_sage_const_431 = Integer(431)
_sage_const_75 = Integer(75)
_sage_const_101 = Integer(101)
_sage_const_443 = Integer(443)
_sage_const_229 = Integer(229)
_sage_const_50 = Integer(50)
_sage_const_2123 = Integer(2123)
_sage_const_900 = Integer(900)


def solve_equation(c1, c2, c3, c4, c5, c6, c7, c8, pw, print_G=False, print_last_poly=False):
    '''
    解方程`(a+b*sqrt(2)+c*sqrt(3)+d*sqrt(5))^pw == c1+c2*sqrt(2)+c3*sqrt(3)+c4*sqrt(5)+c5*sqrt(6)+c6*sqrt(10)+c7*sqrt(15)+c8*sqrt(30)`

    :param c1: 常数项
    :param c2: 根号2的系数
    :param c3: 根号3的系数
    :param c4: 根号5的系数
    :param c5: 根号6的系数
    :param c6: 根号10的系数
    :param c7: 根号15的系数
    :param c8: 根号30的系数
    :param pw: 幂
    :param print_G: 是否打印Grobner基
    :param print_last_poly: 是否打印Grobner基最后一个元素的因式分解
    '''
    S = PolynomialRing(QQ, order='lex', names=('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 's2', 's3', 's5', 's6', 's10', 's15', 's30',))
    (a, b, c, d, e, f, g, h, s2, s3, s5, s6, s10, s15, s30,) = S._first_ngens(15)
    I = S.ideal([s2 ** _sage_const_2 - _sage_const_2, s3 ** _sage_const_2 - _sage_const_3, s5 ** _sage_const_2 - _sage_const_5])
    s6 = s2 * s3
    s10 = s2 * s5
    s15 = s3 * s5
    s30 = s2 * s3 * s5
    Quo = S.quotient(I)
    expr = Quo(a + b * s2 + c * s3 + d * s5 + e * s6 + f * s10 + g * s15 + h * s30)
    expanded = expr ** pw
    rep = expanded.lift()
    v1 = rep.coefficient({s2: _sage_const_0, s3: _sage_const_0, s5: _sage_const_0})
    v2 = rep.coefficient({s2: _sage_const_1, s3: _sage_const_0, s5: _sage_const_0})
    v3 = rep.coefficient({s2: _sage_const_0, s3: _sage_const_1, s5: _sage_const_0})
    v4 = rep.coefficient({s2: _sage_const_0, s3: _sage_const_0, s5: _sage_const_1})
    v5 = rep.coefficient({s2: _sage_const_1, s3: _sage_const_1, s5: _sage_const_0})
    v6 = rep.coefficient({s2: _sage_const_1, s3: _sage_const_0, s5: _sage_const_1})
    v7 = rep.coefficient({s2: _sage_const_0, s3: _sage_const_1, s5: _sage_const_1})
    v8 = rep.coefficient({s2: _sage_const_1, s3: _sage_const_1, s5: _sage_const_1})
    print(v1)
    print(v2)
    print(v3)
    print(v4)
    print(v5)
    print(v6)
    print(v7)
    print(v8)
    G = ideal(v1 - c1, v2 - c2, v3 - c3, v4 - c4, v5 - c5, v6 - c6, v7 - c7, v8 - c8).groebner_basis(algorithm='singular:slimgb')
    if print_G:
        for i, gro in enumerate(G):
            print(f'G[{i}] =', gro)
    last_var_poly = G[-_sage_const_1].factor()
    if print_last_poly:
        print(last_var_poly)
    last_var = h
    sols = solve(SR(last_var_poly), SR(last_var))
    sols = [sol.rhs() for sol in sols if sol.rhs().is_real()]
    var_list = (a, b, c, d, e, f, g, h)
    return G, last_var, var_list, s2, s3, s5, sols, Quo


def back_substitution_with_a_sol(G, last_var, var_list, s2, s3, s5, current_sol):
    solved_vars = {last_var}

    # 从倒数第二项开始向前代入
    for i in range(len(G) - _sage_const_2, -_sage_const_1, -_sage_const_1):
        g = G[i]
        '''
        将已知变量代入
        LLM 的代码在这里报错 TypeError: keys do not match self's parent
        问 LLM ，它胡说八道。但我自己 debug 发现，只需要这么写：
        new_var = next((item for item in var_list if item == rv), None)
        就能让变量的类型正确，这代码也就能跑通了
        '''
        g_sub = g.subs(current_sol)
        if not g_sub:
            continue
        remaining_vars = [v for v in g_sub.variables() if v not in solved_vars]

        if len(remaining_vars) == _sage_const_1:
            rv = remaining_vars[_sage_const_0]
            # 转为符号表达式求解
            g_SR = SR(g_sub)
            try:
                sols_v = solve(g_SR == _sage_const_0, SR(rv))
                if sols_v:
                    sol_val = sols_v[_sage_const_0].rhs()
                    new_var = next((item for item in var_list if item == rv), None)
                    current_sol[new_var] = QQbar(sol_val) if sol_val in QQ else sol_val
                    solved_vars.add(new_var)
                else:
                    break  # 无解
            except Exception as e:
                print('解方程遇到报错', e)
                break  # 求解失败
        elif len(remaining_vars) == _sage_const_0:
            # 已满足，跳过
            continue
        else:
            # 多变量，暂时跳过（实际中 Gröbner 基应为三角形）
            continue

    ret = {str(k): v for k, v in current_sol.items()}
    return ret


def back_substitution(G, d, var_list, s2, s3, s5, sols):
    all_solutions = []
    for val in sols:
        current_sol = {d: QQbar(val) if val in QQ else val}
        current_sol = back_substitution_with_a_sol(G, d, var_list, s2, s3, s5, current_sol)
        all_solutions.append(current_sol)
    return all_solutions


def solve_directly(c1, c2, c3, c4, c5, c6, c7, c8):
    a, b, c, d, e, f, g, h = var('a b c d e f g h')
    v1 = a ** _sage_const_3 + _sage_const_6 * a * b ** _sage_const_2 + _sage_const_9 * a * c ** _sage_const_2 + _sage_const_15 * a * d ** _sage_const_2 + _sage_const_18 * a * e ** _sage_const_2 + _sage_const_30 * a * f ** _sage_const_2 + _sage_const_45 * a * \
        g ** _sage_const_2 + _sage_const_90 * a * h ** _sage_const_2 + _sage_const_36 * b * c * e + _sage_const_60 * b * d * f + _sage_const_180 * b * g * h + _sage_const_90 * c * d * g + _sage_const_180 * c * f * h + _sage_const_180 * d * e * h + _sage_const_180 * e * f * g
    v2 = _sage_const_3 * a ** _sage_const_2 * b + _sage_const_18 * a * c * e + _sage_const_30 * a * d * f + _sage_const_90 * a * g * h + _sage_const_2 * b ** _sage_const_3 + _sage_const_9 * b * c ** _sage_const_2 + _sage_const_15 * b * d ** _sage_const_2 + _sage_const_18 * \
        b * e ** _sage_const_2 + _sage_const_30 * b * f ** _sage_const_2 + _sage_const_45 * b * g ** _sage_const_2 + _sage_const_90 * b * h ** _sage_const_2 + _sage_const_90 * c * d * h + _sage_const_90 * c * f * g + _sage_const_90 * d * e * g + _sage_const_180 * e * f * h
    v3 = _sage_const_3 * a ** _sage_const_2 * c + _sage_const_12 * a * b * e + _sage_const_30 * a * d * g + _sage_const_60 * a * f * h + _sage_const_6 * b ** _sage_const_2 * c + _sage_const_60 * b * d * h + _sage_const_60 * b * f * g + _sage_const_3 * c ** _sage_const_3 + \
        _sage_const_15 * c * d ** _sage_const_2 + _sage_const_18 * c * e ** _sage_const_2 + _sage_const_30 * c * f ** _sage_const_2 + _sage_const_45 * c * g ** _sage_const_2 + _sage_const_90 * c * h ** _sage_const_2 + _sage_const_60 * d * e * f + _sage_const_180 * e * g * h
    v4 = _sage_const_3 * a ** _sage_const_2 * d + _sage_const_12 * a * b * f + _sage_const_18 * a * c * g + _sage_const_36 * a * e * h + _sage_const_6 * b ** _sage_const_2 * d + _sage_const_36 * b * c * h + _sage_const_36 * b * e * g + _sage_const_9 * c ** _sage_const_2 * \
        d + _sage_const_36 * c * e * f + _sage_const_5 * d ** _sage_const_3 + _sage_const_18 * d * e ** _sage_const_2 + _sage_const_30 * d * f ** _sage_const_2 + _sage_const_45 * d * g ** _sage_const_2 + _sage_const_90 * d * h ** _sage_const_2 + _sage_const_180 * f * g * h
    v5 = _sage_const_3 * a ** _sage_const_2 * e + _sage_const_6 * a * b * c + _sage_const_30 * a * d * h + _sage_const_30 * a * f * g + _sage_const_6 * b ** _sage_const_2 * e + _sage_const_30 * b * d * g + _sage_const_60 * b * f * h + _sage_const_9 * c ** _sage_const_2 * \
        e + _sage_const_30 * c * d * f + _sage_const_90 * c * g * h + _sage_const_15 * d ** _sage_const_2 * e + _sage_const_6 * e ** _sage_const_3 + _sage_const_30 * e * f ** _sage_const_2 + _sage_const_45 * e * g ** _sage_const_2 + _sage_const_90 * e * h ** _sage_const_2
    v6 = _sage_const_3 * a ** _sage_const_2 * f + _sage_const_6 * a * b * d + _sage_const_18 * a * c * h + _sage_const_18 * a * e * g + _sage_const_6 * b ** _sage_const_2 * f + _sage_const_18 * b * c * g + _sage_const_36 * b * e * h + _sage_const_9 * c ** _sage_const_2 * \
        f + _sage_const_18 * c * d * e + _sage_const_15 * d ** _sage_const_2 * f + _sage_const_90 * d * g * h + _sage_const_18 * e ** _sage_const_2 * f + _sage_const_10 * f ** _sage_const_3 + _sage_const_45 * f * g ** _sage_const_2 + _sage_const_90 * f * h ** _sage_const_2
    v7 = _sage_const_3 * a ** _sage_const_2 * g + _sage_const_12 * a * b * h + _sage_const_6 * a * c * d + _sage_const_12 * a * e * f + _sage_const_6 * b ** _sage_const_2 * g + _sage_const_12 * b * c * f + _sage_const_12 * b * d * e + _sage_const_9 * c ** _sage_const_2 * \
        g + _sage_const_36 * c * e * h + _sage_const_15 * d ** _sage_const_2 * g + _sage_const_60 * d * f * h + _sage_const_18 * e ** _sage_const_2 * g + _sage_const_30 * f ** _sage_const_2 * g + _sage_const_15 * g ** _sage_const_3 + _sage_const_90 * g * h ** _sage_const_2
    v8 = _sage_const_3 * a ** _sage_const_2 * h + _sage_const_6 * a * b * g + _sage_const_6 * a * c * f + _sage_const_6 * a * d * e + _sage_const_6 * b ** _sage_const_2 * h + _sage_const_6 * b * c * d + _sage_const_12 * b * e * f + _sage_const_9 * c ** _sage_const_2 * \
        h + _sage_const_18 * c * e * g + _sage_const_15 * d ** _sage_const_2 * h + _sage_const_30 * d * f * g + _sage_const_18 * e ** _sage_const_2 * h + _sage_const_30 * f ** _sage_const_2 * h + _sage_const_45 * g ** _sage_const_2 * h + _sage_const_30 * h ** _sage_const_3
    sols = solve([
        v1 - c1, v2 - c2, v3 - c3, v4 - c4, v5 - c5, v6 - c6, v7 - c7, v8 - c8
    ])
    print(sols)


# 跑不出结果
solve_directly(
    _sage_const_2848 /
    _sage_const_135,
    _sage_const_1213 /
    _sage_const_60,
    _sage_const_704 /
    _sage_const_45,
    _sage_const_431 /
    _sage_const_75,
    _sage_const_101 /
    _sage_const_12,
    _sage_const_443 /
    _sage_const_75,
    _sage_const_229 /
    _sage_const_50,
    _sage_const_2123 /
    _sage_const_900)
G, last_var, var_list, s2, s3, s5, sols, _ = solve_equation(_sage_const_2848 /
                                                            _sage_const_135, _sage_const_1213 /
                                                            _sage_const_60, _sage_const_704 /
                                                            _sage_const_45, _sage_const_431 /
                                                            _sage_const_75, _sage_const_101 /
                                                            _sage_const_12, _sage_const_443 /
                                                            _sage_const_75, _sage_const_229 /
                                                            _sage_const_50, _sage_const_2123 /
                                                            _sage_const_900, _sage_const_3, True, True)
