

# This file was *autogenerated* from the file 5-绝谷野樵化简根式/只有一个根式.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
_sage_const_1 = Integer(1)
_sage_const_2 = Integer(2)
_sage_const_4 = Integer(4)
_sage_const_50 = Integer(50)
_sage_const_1en10 = RealNumber('1e-10')
_sage_const_3 = Integer(3)
_sage_const_5 = Integer(5)
_sage_const_6 = Integer(6)
_sage_const_7 = Integer(7)
_sage_const_15 = Integer(15)
_sage_const_67 = Integer(67)
_sage_const_11 = Integer(11)
_sage_const_72 = Integer(72)
_sage_const_161 = Integer(161)


def simplify_nested_sqrt(c1, c2, c3):
    """
    尝试将 sqrt(c1 + c2*sqrt(c3)) 化为 sqrt(a) ± sqrt(b)，其中 a,b ∈ QQ, a,b ≥ 0.
    要求 c1, c2, c3 ∈ QQ，且 c3 > 0.

    返回 (a, b, sgn) 使得 sqrt(c1 + c2*sqrt(c3)) == sqrt(a) + sgn*sqrt(b),
    其中 sgn = +1 if c2 >= 0, else -1.
    若无法表示为这种形式，则返回 None.
    """
    # 确保输入是有理数
    c1 = QQ(c1)
    c2 = QQ(c2)
    c3 = QQ(c3)

    if c3 <= _sage_const_0:
        raise ValueError("c3 must be positive rational")

    # 特殊情况： c2 == 0 ，则原式 = sqrt(c1)，只需检查 c1 是否为平方数
    if c2 == _sage_const_0:
        if c1 < _sage_const_0:
            return None
        sqrt_c1 = sqrt(c1)
        if sqrt_c1 in QQ:
            return (c1, _sage_const_0, _sage_const_1)
        else:
            return None

    sgn = _sage_const_1 if c2 > _sage_const_0 else -_sage_const_1

    R = QQ['x']
    (x,) = R._first_ngens(1)
    poly = x ** _sage_const_2 - c1 * x + (c2 ** _sage_const_2 * c3) / _sage_const_4

    roots = poly.roots(multiplicities=False)

    if len(roots) != _sage_const_2:
        # 判别式非完全平方，根不在 QQ 中
        return None

    a, b = roots[_sage_const_0], roots[_sage_const_1]

    if a < _sage_const_0 or b < _sage_const_0:
        return None

    lhs = sqrt(c1 + c2 * sqrt(c3))
    rhs1 = sqrt(a) + sgn * sqrt(b)
    rhs2 = sqrt(b) + sgn * sqrt(a)
    if abs(lhs.n(_sage_const_50) - rhs1.n(_sage_const_50)) < _sage_const_1en10:
        return (a, b, sgn)
    if abs(lhs.n(_sage_const_50) - rhs2.n(_sage_const_50)) < _sage_const_1en10:
        return (b, a, sgn)
    return None


if __name__ == "__main__":
    '''
    https://zhuanlan.zhihu.com/p/663659377
    (2, 1, 1) sqrt(3 + 2*sqrt(2)) = sqrt(2) + sqrt(1)
    (3, 2, -1) sqrt(5 - 2*sqrt(6)) = sqrt(3) - sqrt(2)
    (4, 3, 1)
    (4, 3, -1)
    (5/2, 3/2, -1) (根号10-根号6)/2
    None 无法化简
    (49/6, 3, 1) 7/6*sqrt(6) + sqrt(3)
    (9, 2, -1) 3 - sqrt(2)
    (9/2, 3/2, -1) (3*sqrt(2) - sqrt(6))/2
    '''
    cases = [
        (_sage_const_3, _sage_const_2, _sage_const_2),
        (_sage_const_5, -_sage_const_2, _sage_const_6),
        (_sage_const_7, _sage_const_4, _sage_const_3),
        (_sage_const_7, -_sage_const_4, _sage_const_3),
        (_sage_const_4, -_sage_const_1, _sage_const_15),
        (_sage_const_1, _sage_const_1, _sage_const_3),
        (_sage_const_67 / _sage_const_6, _sage_const_7, _sage_const_2),
        (_sage_const_11, -_sage_const_1, _sage_const_72),
        (_sage_const_6, -_sage_const_3, _sage_const_3),
        (_sage_const_15, -_sage_const_1, _sage_const_161),
    ]
    for cas in cases:
        result = simplify_nested_sqrt(*cas)
        print(result)
