

# This file was *autogenerated* from the file 5-绝谷野樵化简根式/平四根式示例_求解失败.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_1 = Integer(1)
_sage_const_4 = Integer(4)
_sage_const_5 = Integer(5)
_sage_const_8 = Integer(8)
_sage_const_6 = Integer(6)
_sage_const_3 = Integer(3)
_sage_const_7 = Integer(7)  # sqrt(1 + (sqrt(2) - 5/4) ^ 0.25)
S = PolynomialRing(QQ, order='lex', names=('x',))
(x,) = S._first_ngens(1)
eq = ((x ** _sage_const_2 - _sage_const_1) ** _sage_const_4 + _sage_const_5 / _sage_const_4) ** _sage_const_2 - _sage_const_2
eq_factor = eq.factor()
print(eq, eq_factor)
# (x^8 - 4*x^6 - 2*x^5 + 6*x^4 + 6*x^3 - 2*x^2 - 5*x - 7/4) * (x^8 - 4*x^6 + 2*x^5 + 6*x^4 - 6*x^3 - 2*x^2 + 5*x - 7/4)
# 可以写成 f(x) * f(-x) = 0
eq1 = x ** _sage_const_8 - _sage_const_4 * x ** _sage_const_6 - _sage_const_2 * x ** _sage_const_5 + _sage_const_6 * x ** _sage_const_4 + \
    _sage_const_6 * x ** _sage_const_3 - _sage_const_2 * x ** _sage_const_2 - _sage_const_5 * x - _sage_const_7 / _sage_const_4
sols = solve(SR(eq1), SR(x))  # 解方程失败
# sols = SR(eq1).roots()  # RuntimeError: no explicit roots found
print(sols)
# 画出函数图像，可以看到两个数值解。但这意义不大，因为猜不到数值解的解析形式
