

# This file was *autogenerated* from the file 4-pku_2021_again/poly_inv_demo.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3)
_sage_const_2 = Integer(2)
_sage_const_1 = Integer(1)
_sage_const_4 = Integer(4)
R = PolynomialRing(QQ, names=('c',))
(c,) = R._first_ngens(1)
f = c ** _sage_const_3 - _sage_const_3 * c ** _sage_const_2 + _sage_const_3
K = R.quotient(f, 'cbar')
cbar = K.gen()

denom = _sage_const_1 + cbar - cbar ** _sage_const_2
inv_denom = denom.inverse()
print('1 + c - c^2 的逆元', inv_denom)

lhs1 = cbar * inv_denom
rhs1 = -cbar ** _sage_const_3 + _sage_const_2 * cbar ** _sage_const_2 + cbar  # 也可以写 K(-c^3 + 2c^2 + c)
print('c / (1 + c - c^2) =', lhs1)
print('rhs1 =', rhs1, lhs1 == rhs1)

lhs2 = K(c * (_sage_const_1 - c)) * inv_denom
rhs2 = K(c ** _sage_const_4 - _sage_const_3 * c ** _sage_const_3 + c ** _sage_const_2 + c)
print('c(1-c) / (1 + c - c^2) =', lhs2, rhs2, lhs2 == rhs2)

# PPT 里提到的初中常规题，直接这么写就能映射到商环里
wanted = K(c ** _sage_const_4 - _sage_const_4 * c ** _sage_const_3 + _sage_const_3 * c ** _sage_const_2 + _sage_const_3 * c)
print(wanted)
