

# This file was *autogenerated* from the file 6-求旋转曲面方程/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)
_sage_const_1 = Integer(1)
_sage_const_2 = Integer(2)
_sage_const_50 = Integer(50)
_sage_const_30 = Integer(30)


def compute_surface_of_revolution(curve_exprs, line_exprs):
    """
    计算旋转曲面方程
    :param curve_exprs: 曲线参数方程列表 [x_c(t), y_c(t), z_c(t)]
    :param line_exprs:  直线参数方程列表 [x_l(s), y_l(s), z_l(s)]
    :return: 曲面方程 f(x,y,z) = 0 的多项式
    """
    print("正在初始化变量与环...")

    # 1. 定义符号变量
    # t: 曲线参数，s: 直线参数 (仅用于提取几何量，不参与消元), x,y,z: 空间坐标
    var('t s x y z')

    # 2. 提取直线的几何信息 (定点 A 和 方向向量 V)
    # 直线 L(s) = A + s * V
    # 取 s=0 得到定点 A
    A = [expr.subs(s=_sage_const_0) for expr in line_exprs]
    # 取 s=1 和 s=0 的差值得到方向向量 V (假设是直线，s 是线性的)
    V = [expr.subs(s=_sage_const_1) - expr.subs(s=_sage_const_0) for expr in line_exprs]

    # 检查方向向量是否为零向量
    if all(v == _sage_const_0 for v in V):
        raise ValueError("直线的方向向量为零，请输入有效的直线方程。")

    # 3. 构建多项式方程组
    # 曲线上的动点 Q(t)
    Q = curve_exprs

    # 空间动点 P(x,y,z)
    P = [x, y, z]

    # --- 方程 1: 轴向投影相等 (Dot Product Condition) ---
    # (P - A) . V = (Q - A) . V
    # 移项使得右边为 0: (P - A) . V - (Q - A) . V = 0
    proj_P = sum((p - a) * v for p, a, v in zip(P, A, V))
    proj_Q = sum((q - a) * v for q, a, v in zip(Q, A, V))
    eq1 = proj_P - proj_Q

    # --- 方程 2: 到轴距离平方相等 (Distance Squared Condition) ---
    # |(P - A) x V|^2 = |(Q - A) . V|^2
    # 叉积模长平方公式：|U x V|^2 = |U|^2|V|^2 - (U . V)^2
    # 或者直接计算叉积分量平方和。为了保持多项式形式，直接计算分量。
    def cross_product_sq(U, V_vec):
        # U, V_vec are lists of 3 elements
        cx = U[_sage_const_1] * V_vec[_sage_const_2] - U[_sage_const_2] * V_vec[_sage_const_1]
        cy = U[_sage_const_2] * V_vec[_sage_const_0] - U[_sage_const_0] * V_vec[_sage_const_2]
        cz = U[_sage_const_0] * V_vec[_sage_const_1] - U[_sage_const_1] * V_vec[_sage_const_0]
        return cx ** _sage_const_2 + cy ** _sage_const_2 + cz ** _sage_const_2

    vec_AP = [p - a for p, a in zip(P, A)]
    vec_AQ = [q - a for q, a in zip(Q, A)]

    dist_sq_P = cross_product_sq(vec_AP, V)
    dist_sq_Q = cross_product_sq(vec_AQ, V)

    eq2 = dist_sq_P - dist_sq_Q

    print("已构建几何约束方程。")
    print(f"方程 1 (投影): {eq1 == _sage_const_0}")
    print(f"方程 2 (距离): {eq2 == _sage_const_0}")

    # 4. 定义多项式环并转换方程
    # 为了使用 Grobner 基消元，我们需要在多项式环中操作。
    # 顺序非常重要：为了消去 t，我们需要 t 的优先级高于 x, y, z。
    # 使用字典序 'lex'，变量顺序设为 t, x, y, z。
    # 注意：这里假设系数为有理数 QQ。如果包含无理数，可能需要扩域或保持符号环 (但符号环 GB 计算较慢)。
    try:
        R = PolynomialRing(QQ, 't,x,y,z', order='lex')
        # 将符号表达式转换为环中的多项式
        # 使用 R() 进行转换，如果表达式包含非有理数系数可能会报错
        f1 = R(eq1)
        f2 = R(eq2)
    except TypeError:
        print("警告：检测到非有理数系数。尝试使用符号环 (SR) 作为基域，计算速度可能较慢。")
        R = PolynomialRing(SR, 't,x,y,z', order='lex')
        f1 = R(eq1)
        f2 = R(eq2)

    # 5. 计算 Grobner 基
    print("正在计算 Grobner 基 (这可能需要一些时间)...")
    I = R.ideal([f1, f2])
    G = I.groebner_basis()

    return G[-_sage_const_1]

    # 6. 提取不含参数 t 的多项式
    # 在 lex 序 (t > x > y > z) 下，消元理想 G \cap QQ[x,y,z] 的元素会出现在基的后面
    # surface_polys = [g for g in G if 't' not in g.variables()]

    # if not surface_polys:
    #     return "未找到独立的曲面方程 (可能曲线在轴上或退化)。"

    # f_surface = surface_polys[0]

    # if f_surface.base_ring() == QQ:
    #     f_surface = f_surface.content() * f_surface.primitive_part()

    # return f_surface


if __name__ == "__main__":
    print("=" * _sage_const_50)
    print("Hans7 的旋转曲面求解器")
    print("=" * _sage_const_50)

    var('t s')
    print("\n请输入曲线的参数方程 (变量为 t):")
    try:
        cx = SR(input("x(t) = "))
        cy = SR(input("y(t) = "))
        cz = SR(input("z(t) = "))
        curve = [cx, cy, cz]

        print("\n请输入直线的参数方程 (变量为 s):")
        lx = SR(input("x(s) = "))
        ly = SR(input("y(s) = "))
        lz = SR(input("z(s) = "))
        line = [lx, ly, lz]
    except Exception as e:
        print(f"输入解析错误：{e}")
        print("提示：请确保输入合法的 Sage 表达式，乘法需加 * 号 (如 2*t)")
        exit(_sage_const_1)

    print("\n输入曲线：x=t, y=0, z=t^2")
    print("输入直线：x=0, y=0, z=s (z 轴)")
    print("-" * _sage_const_30)

    try:
        result_poly = compute_surface_of_revolution(curve, line)
        print("-" * _sage_const_30)
        print("计算完成！曲面方程 f(x,y,z) = 0 为：")
        print(f"{result_poly} = 0")
        print("\n(注：若结果包含常数因子，不影响方程几何意义)")

    except Exception as e:
        print(f"发生错误：{e}")
        print("请检查输入方程是否为多项式形式，且系数是否兼容。")
