

# This file was *autogenerated* from the file 6-求旋转曲面方程/examples.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2)
_sage_const_3 = Integer(3)
_sage_const_4 = Integer(4)
_sage_const_1 = Integer(1)
_sage_const_0 = Integer(0)
_sage_const_30 = Integer(30)
import traceback

load('6-求旋转曲面方程/compute.sage')
var('t s x y z')
cases = [
    [[_sage_const_2 - t, _sage_const_3 * t - _sage_const_4, t - _sage_const_1], [_sage_const_2 * s + _sage_const_2, s + _sage_const_4, _sage_const_3 * s + _sage_const_1]],
    [[_sage_const_3, _sage_const_4, t], [_sage_const_0, _sage_const_0, s]],
]
for curve, line in cases:
    print("-" * _sage_const_30)
    print(f"曲线：{curve}")
    print(f"直线：{line}")
    try:
        result_poly = compute_surface_of_revolution(curve, line)
        print("-" * _sage_const_30)
        print("计算完成！曲面方程 f(x,y,z) = 0 为：")
        print(f"{result_poly} = 0")
        print("\n(注：若结果包含常数因子，不影响方程几何意义)")

    except Exception as e:
        print(f"发生错误：{e}")
        print("请检查输入方程是否为多项式形式，且系数是否兼容。")

xyz_cases = [
    [[_sage_const_2 * x ** _sage_const_2 + y ** _sage_const_2 - _sage_const_1, z], [_sage_const_0, t, _sage_const_0]],
    [[_sage_const_2 * x ** _sage_const_2 + y ** _sage_const_2 - _sage_const_1, z], [t, _sage_const_0, _sage_const_0]],
    [[z - y ** _sage_const_2, x], [_sage_const_0, t, _sage_const_0]],
    [[z - y ** _sage_const_2, x], [_sage_const_0, _sage_const_0, t]],
]
for curve, line in xyz_cases:
    print("-" * _sage_const_30)
    print(f"曲线：{curve}")
    print(f"直线：{line}")
    try:
        result_poly = compute_surface_of_revolution_xyz(curve, line)
        print("-" * _sage_const_30)
        print("计算完成！曲面方程 f(x,y,z) = 0 为：")
        print(f"{result_poly} = 0")
        print("\n(注：若结果包含常数因子，不影响方程几何意义)")

    except Exception as e:
        print(f"发生错误：{e}")
        traceback.print_exc()
        print("请检查输入方程是否为多项式形式，且系数是否兼容。")
